git fetch MihailovYA
git fetch MedvedevGO
git fetch AzarevichAD
git fetch FialkovskyMS
git fetch PolyakovNS
git fetch ShevelevaAM
git fetch KaramyshevAO
git fetch ShiryaevYA
git fetch SergukhinVU
git fetch AfiychukII
git fetch GomonovaAA
git fetch LavrenkovaEL
git fetch TereshchenkoVN
git fetch KalashnikovMA
git fetch SharipovaR
git fetch VergeychikGL
git fetch VerohaVN
git fetch FedianinNI
git fetch NikitinKV
git fetch SpasAA
git fetch KuharevMA
git fetch LopatinaAS
git fetch BykovIV
git fetch MeyzerDV
git fetch GerasimovaDV
git fetch MiheevaEE
git fetch StepanovaSI
git fetch TimofeevDA
git fetch YakovlevEA
git fetch BazarovIA
git fetch LunchukDV
git fetch LavrenkovaEL
git fetch TokunMS

