git remote add os18 git@github.com:JAkutenshi/leti_os_2018.git
git remote add MihailovYA https://github.com/YuraMihailov123/leti_os_2018.git
git remote add VergeychickGL https://github.com/gglebaty/leti_os_2018.git
git remote add MedvedevGO https://github.com/glebmedvedev/leti_os_2018.git
git remote add AzarevichAD https://github.com/Trasil/leti_os_2018.git
git remote add FialkovskyMS https://github.com/makometr/leti_os_2018.git
git remote add PolyakovNS https://github.com/HECTOPK/leti_os_2018.git
git remote add ShevelevaAM https://github.com/ShevelevaAnna/leti_os_2018.git
git remote add KaramyshevAO https://github.com/NotForU2/leti_os_2018.git
git remote add ShiryaevYA https://github.com/yar1k112/leti_os_2018.git
git remote add SergukhinVU https://github.com/SergukhinVU/leti_os_2018.git
git remote add AfiychukII https://github.com/afiychuk/leti_os_2018.git
git remote add GomonovaAA https://github.com/AsyaGom/leti_os_2018.git
git remote add LavrenkovaEL https://github.com/lavrenkova/leti_os_2018.git
git remote add TereshchenkoVN https://github.com/vika210899/leti_os_2018.git
git remote add KalashnikovMA https://github.com/Transliteration/leti_os_2018.git
git remote add SharipovaR https://github.com/ranagul/leti_os_2018.git
git remote add VerohaVN https://github.com/veronav/leti_os_2018.git
git remote add FedianinNI https://github.com/NIKFED/leti_os_2018.git
git remote add NikitinKV https://github.com/NikitinKirill/leti_os_2018.git
git remote add SpasAA https://github.com/spasartyom/leti_os_2018.git
git remote add KuharevMA https://github.com/MikeKuh/leti_os_2018.git
git remote add LopatinaAS https://github.com/Anastasiyalopatina/leti_os_2018.git
git remote add BykovIV https://github.com/BykovIlya/leti_os_2018.git
git remote add MeyzerDV https://github.com/Denmey/leti_os_2018.git
git remote add GerasimovaDV https://github.com/darinagerasimova/leti_os_2018.git
git remote add MiheevaEE https://github.com/katierm/leti_os_2018.git
git remote add StepanovaSI https://github.com/PeppaPig153/leti_os_2018.git
git remote add TimofeevDA https://github.com/datdimotim/leti_os_2018.git
git remote add YakovlevEA https://github.com/EgorYackovleff/leti_os_2018.git
git remote add BazarovIA https://github.com/ilmb/leti_os_2018.git
git remote add DainovichA https://github.com/aDainovich/leti_os_2018.git
git remote add TokunMS https://github.com/Creedy0/leti_os_2018.git
